### ISSUE TITLE
Architecture review for better integration with Symfony

### ISSUE THREAD

**Issue by stof** [halloverden/symfony-route-deprecation-bundle#6]
Hi. First of all, congrats for releasing your package for public use.

I reviewed its architecture, and I have a suggestion to better integrate it with Symfony. This is meant as an opportunity to improve it. You are free to refactor the package or ignore this suggestion as you prefer.

Shortcomings of the current implementation:
- it works only for annotation-based route definitions, while Symfony supports many other ways (XML, Yaml, PHP, custom loaders, etc...)
- it parses the annotation again at runtime and tries to associate it with the route definition. This logic has several shortcomings:
     - it searches only for `@DeprecatedRoute` annotations, and so won't deal fine with cases where a class-level `@DeprecatedRoute` annotation is overriden by a method-level `@Route` annotation, so would use a different route definition that the routing layer
    - the matching of route names accepts any substring, which might cause issues depending on the naming convention of routes (it is valid to have one route name being a substring of another one)

A solution to this could be to change the way deprecations are configured for a route. The canonical representation would become `_deprecated_since` and `_deprecated_sunset` attributes (the names can be challenged of course. Prefixing them with `_` is a convention to avoid conflicts with route parameters), which can be set with any loaders (using defaults). the `@DeprecatedRoute` annotation can be kept as a DX improvement, changing its internal implementation to set the defaults.
The event listener would then be able to run on `KernelEvents::RESPONSE` only, reading these attributes and using them to set the headers.

**Comment by marco-giannetti** [comment]
Hi, thank you for your feedback, I really appreciate it!

As you mentioned, we might need to expand our support to other Route definitions, if possible, and I think it will be the focus of the next few issues.
As for the other points, the `@DeprecatedRoute` annotation is not supposed to be overridden by `@Route`, even when on methods: the intention behind it is that if the entire Controller is deprecated, then all routes in that class are deprecated as well, and can only be overriden by other `@DeprecatedRoute` annotations. If some of the routes in the controller must not be deprecated then the deprecation annotations must be set on the single methods that are to be deprecated and not on the Controller.
About the third point, the name matching is provided as a way to determine whether a path should be considered deprecated or not. This is useful because a method could have both a `@Route` and `@DeprecatedRoute` annotations, specifying different paths, for example:
```
/**
   * @DeprecatedRoute("/check", methods={"GET"}, name="check", since="01-01-2020", until="15-07-2020", enforce=true)
   * @Route("/is-valid", methods={"GET"}, name="is-valid")
   */
  public function isValid() {
    // do stuff
  }
```
In this case the method `isValidEmail` is perfectly valid. The deprecation headers are only set when invoking the `/check` path, and not the `/is-valid` path and there is no conflict with other routes or controllerMethods, the check is only on the method itself, to see if the deprecated path was invoked or not. In this case I realize that the name parameter in the `@Route` can't be a substring of the name parameter in `@DeprecatedRoute`. `@Route("/is-valid", methods={"GET"}, name="chec")`, for example, would match and cause the path to be deprecated.

As for your solution, it seems to be quite valid, I'll make sure to explore it, thank you again for your suggestions!

**Comment by stof** [comment]
> As for the other points, the `@DeprecatedRoute` annotation is not supposed to be overridden by `@Route`, even when on methods: the intention behind it is that if the entire Controller is deprecated, then all routes in that class are deprecated as well, and can only be overriden by other `@DeprecatedRoute` annotations. If some of the routes in the controller must not be deprecated then the deprecation annotations must be set on the single methods that are to be deprecated and not on the Controller.

the thing is, from the loading of routes PoV, it is possible to mix `@Route` and the `@DeprecatedRoute` child class (as the Symfony annotation loader does not even know about the child class.
but your code only looks at the child class, which can create weird cases where the route definitions you look at is not the one used for matching (the standard usage should not suffer from it, indeed. But for a public bundle, you cannot be sure that users will stay in this intended usage)

> In this case I realize that the name parameter in the `@Route` can't be a substring of the name parameter in `@DeprecatedRoute`. `@Route("/is-valid", methods={"GET"}, name="chec")`, for example, would match and cause the path to be deprecated.

that's precisely the issue I'm reporting.

**Comment by stof** [comment]
note that my suggested solution solves all these issues, as it decouples the listener entirely from the way the route is defined.

**Comment by marco-giannetti** [comment]
> note that my suggested solution solves all these issues, as it decouples the listener entirely from the way the route is defined.

That's what I thought! I'll make sure to test it and link the PR here.
